### ISSUE TITLE
PG::UndefinedColumn: ERROR:  column "completed_at" does not exist (deploys table)

### ISSUE THREAD

**Issue by hesco** [houston/houston-core#126]
Now running into data integrity issues here.  -- Hugh 

```
root@houston:/opt/local/houston# bundle exec rake db:migrate 
/opt/local/houston/vendor/ruby/2.2.0/gems/htmlentities-4.3.2/lib/htmlentities/mappings/expanded.rb:465: warning: duplicated key at line 466 ignored: "inodot"
[config] default host: localhost:3000
Skipping timers since we're not running as a server
== 20121225175106 ReplaceEnvironmentIdWithEnvironmentName: migrating ==========
-- add_column(:deploys, :environment_name, :string, {:null=>false, :default=>"Production"})
   -> 0.1724s
-- add_index(:deploys, :environment_name)
   -> 0.0632s
-- add_index(:deploys, [:project_id, :environment_name])
   -> 0.0499s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedColumn: ERROR:  column "completed_at" does not exist
LINE 1: SELECT "deploys".* FROM "deploys"   ORDER BY completed_at DE...
                                                     ^
: SELECT "deploys".* FROM "deploys"   ORDER BY completed_at DESC/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/connection_adapters/postg
resql_adapter.rb:822:in `async_exec'
```

**Comment by hesco** [comment]
application of this:

```
houston_poc=# ALTER TABLE deploys ADD COLUMN completed_at integer;
```

results in this on the houston container:

```
Skipping timers since we're not running as a server
You have 119 pending migrations:
  20121225175106 ReplaceEnvironmentIdWithEnvironmentName
  20121230173644 SetMupHstore

<snip>

== 20121225175106 ReplaceEnvironmentIdWithEnvironmentName: migrated (0.7526s) =

```
My choice of integer was for the simplest sortable data type, and not based on any code review, past what was exposed in the error message above.  I may very well have gotten that one wrong here.

**Comment by hesco** [comment]
```
== 20150323004452 AddDeploysCompletedAt: migrating ============================
-- add_column(:deploys, :completed_at, :timestamp)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateColumn: ERROR:  column "completed_at" of relation "deploys" already exists
: ALTER TABLE "deploys" ADD COLUMN "completed_at" timestamp/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/connection_adapters/postgresql
/database_statements.rb:128:in `async_exec'
```

so back on the db server I go:

```
houston_poc=# ALTER TABLE deploys DROP COLUMN completed_at;
ALTER TABLE
```

**Comment by boblail** [comment]
`script/bootstrap` executes

```bash
bundle exec rake db:create db:migrate || exit
```

but for a brand-new database this would probably be better:

```bash
bundle exec rake db:setup || exit
```

I'd like to run `db:setup` for the zero-state and `db:migrate` once the database is relatively current. I wonder if there's a way to do that... Or if it makes sense for `script/bootstrap` to be consigned to one-time use...

**Comment by boblail** [comment]
With `v0.5.1` of `houston-core`, I documented [the recommended way of setting up a new instance](https://github.com/houston/houston-core#getting-started) (`bin/setup` > `rake db:migrate`)

```
houston new my-houston
cd my-houston
< modify config/database.yml >
bin/setup
```
